name: Build and test
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: .NET restore & Build
        run: dotnet build

      - name: Run Postgres in a Container
        uses: hoverkraft-tech/compose-action@v2.0.1

      - name: .NET test
        run: dotnet test 

      # Job to run after PR merge:
      # Version & tag
      # dotnet Package
      # nuget push